# This file just needs to exists from pre-commit
[package]
name = "pre-commit_mirrors-taplo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
